---
title: "randomwalk"
author: "Lorenzo Casini"
date: "03/07/2019"
output: html_document
---

#Problem 1 Fizz Buzz

```{r}
i=1
for(i in 1:100){
if(i%%3==0 & !i%%5==0){print("fizz")} 
else if(i%%5==0 & !i%%3==0){print("buzz")} 
else if(i%%3==0 & i%%5==0){print("fizzbuzz")}
else{print(i)}
}
```

```{r}
for (i in 1:100) {
 if (i %% 3 == 0 & i %% 5 == 0) {print("FizzBuzz")}
 else if (i %% 3 == 0) {print("Fizz")}
 else if (i %% 5 == 0) {print("Buzz")}
 else print(i)
}
```

#Problem 2 map

```{r}
install.packages("ggmap")
```

```{r}
library(ggmap)
```
`
#Problem 3 Random Walk

```{r}
library(plot3D)

```

```{r}
set.seed(1982) #Control seed
steps <- 10^4 #Number of steps
Ut <- runif(steps)
head(Ut)


# Direction probability 
probs <- c(0.167, 0.333, 0.5, 0.667, 0.833)
#initial matrix
step_direction <- matrix(0, steps+1, 3) 
#start random walk
for (i in seq(2, steps+1)){
   Ut = runif(1) #draw random number from U(0,1)
 # Go right if Ut \in [0,prob[1])
  if (Ut < probs[1]) {step_direction[i,1] = 1}

  # Go left if It \in [probs[1], probs[2])
 else if (Ut >= probs[1] && Ut < probs[2]) {step_direction[i,1] = -1}

  # Go forward if Ut \in [probs[2], probs[3])
 else if (Ut >= probs[2] && Ut < probs[3]) {step_direction[i,2] = 1}

  # Go backward if Ut \in [probs[3],probs[4])
 else if (Ut >= probs[3] && Ut < probs[4]) {step_direction[i,2] = -1}
   
     # Go upward if Ut \in [probs[4], probs[5])
 else if (Ut >= probs[4] && Ut < probs[5]) {step_direction[i,3] = 1}
   

  # Go downward if Ut \in [probs[5],1)
 else if (Ut >= probs[5]) {step_direction[i,3] = -1}
}
   
 #cumulative steps
position = data.frame(x = cumsum(step_direction[, 1]), 
                      y = cumsum(step_direction[, 2]),
                      z= cumsum(step_direction[, 3]))

```

```{r}
library(plot3D)
D <- position
scatter3D(D[1:10^4,1], D[1:10^4,2], D[1:10^4,3], xlab = "", ylab = "", zlab = "",phi = 0, theta = 45, bty = "g", type = "l", ticktype = "detailed", lwd = 0.6, colvar = NULL)
points3D(0,0,0, col = "#f8766d", add = TRUE, colkey = FALSE, pch = 20, cex = 1.5)
points3D(26,-44,26, col = "#00bfc4", add = TRUE, colkey = FALSE, pch = 20, cex = 1.5)
```

# Problem 4 Portfolio